name = "Masamune"
license = "MIT"
licenselink = ""
description = "2column, Category, Tag"
homepage = "http://mzgkworks.com/"
tags = ["blog"]
features = ["blog"]
min_version = 0.01

[author]
    name = "mzgk"
    homepage = "http://mzgkworks.com/"
