# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Masamune"
license = "MIT"
licenselink = "https://github.com/mzgk/masamune/blob/master/LICENSE.md"
description = "Simple 2 column blog theme."
homepage = "http://mzgkworks.com/"
tags = ["blog", "2 column"]
features = ["", ""]
min_version = 0.15

[author]
  name = "mzgk"
  homepage = "http://mzgkworks.com"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
